labels:
    sql_path: 'src/o2sk_utils/labels/sql/labels_daily.sql'
    labels_path: 'C:\\Users\\doube\\o2sk\\o2sk-utils\\data\\labels\\'
features:
    sql_path: 'src/o2sk_utils/features/sql/subscriber_behaviour.sql'
    training:
      features_path: 'C:\\Users\\doube\\o2sk\\o2sk-utils\\data\\features\\'
    scoring:
      features_path: '/tmp/x0659133/nbo-engine/data/features/subscriber_behaviour/'
preprocessing:
    pipeline:
      categ_pipe:
        basic:
          ['Inputter:missing']
        advanced:
          ['One_hot_encoder:10']
      int_pipe:
        basic:
          ['Inputter:missing']
        stats:
          ['Truncate_99']
      decimal_pipe:
        basic:
          ['Inputter:missing']
        stats:
          ['Truncate_99', 'LogScaler']
      flag_pipe: 
        basic:
          ['Inputter:-1']
      float_pipe: 
        basic:
          ['Inputter:missing']
        stats:
          ['Truncate_99']
    training:
      features_path: 'C:\\Users\\doube\\o2sk\\o2sk-utils\\data\\features\\'
      labels_path: 'C:\\Users\\doube\\o2sk\\o2sk-utils\\data\\labels\\'
      stats_path: 'C:\\Users\\doube\\o2sk\\stats.json'
      split_col: 'ID_COL_MONTH'
      train_path: 'C:\\Users\\doube\\o2sk\\o2sk-utils\\train'
      valid_path: 'C:\\Users\\doube\\o2sk\\o2sk-utils\\valid'
      test_path: 'C:\\Users\\doube\\o2sk\\o2sk-utils\\test'
      shift_join: -1
      test_months: 0
    scoring:
      features_path: 'C:\\Users\\doube\\o2sk\\o2sk-utils\\data\\features\\'
      stats_path: 'C:\\Users\\doube\\o2sk\\stats.json'
      scoring_output_path: 'C:\\Users\\doube\\o2sk\\o2sk-utils\\scoring'
modeling:
    mode: 'hyperopt' # runs hyperparameter optimization. If cv it takes the best_params from best_params path
    eval_metric: 'aucpr' # mlogloss for multiclass
    objective: 'binary:logistic' # multi:softprob for multiclass
    scale_pos_weight: '400'
    max_depth: [5, 30]
    eta: [0.001, 0.01]  
    subsample: [0.01, 0.6]
    gamma: [1, 30]
    min_child_weight: [1, 50]
    colsample_bytree: [0.3, 1]
    config_path: /home/frovis/o2_sk/xgboost-python-pyspark/docker/config.yml
    docker_config_path: /home/frovis/o2_sk/xgboost-python-pyspark/docker/config_tmp.yml
    data_path: /home/frovis/o2_sk/xgboost-python-pyspark/docker/data/
    log_path: /home/frovis/o2_sk/xgboost-python-pyspark/docker/experiment/binary_training.log
    params_result_path: /home/frovis/o2_sk/xgboost-python-pyspark/docker/experiment/binary_results.csv
    best_params_path: /home/frovis/o2_sk/xgboost-python-pyspark/docker/experiment/binary.yml
    model_path: /home/frovis/o2_sk/xgboost-python-pyspark/docker/experiment/
scoring:
    model_path: '/home/frovis/o2_sk/xgboost-python-pyspark/docker/experiment/model.bin'
    features_path: '/home/frovis/o2_sk/xgboost-python-pyspark/docker/data/'
    scoring_output_path: '/home/frovis/o2_sk/xgboost-python-pyspark/docker/experiment/'

auth_cfg: '/home/o2spark/config.ini'