
labels:
    sql_path: 'src/o2sk_utils/labels/sql/labels_daily.sql'
    labels_path: 'C:\\Users\\doube\\o2sk\\o2sk-utils\\data\\labels\\'
features:
    sql_path: 'src/o2sk_utils/features/sql/subscriber_behaviour.sql'
    training:
      features_path: 'C:\\Users\\doube\\o2sk\\o2sk-utils\\data\\features\\'
    scoring:
      features_path: '/tmp/x0659133/nbo-engine/data/features/subscriber_behaviour/'
preprocessing:
    pipeline:
      categ_pipe:
        basic:
          ['Inputter:missing']
        advanced:
          ['One_hot_encoder:10']
      int_pipe:
        basic:
          ['Inputter:missing']
        stats:
          ['Truncate_99']
      decimal_pipe:
        basic:
          ['Inputter:missing']
        stats:
          ['Truncate_99', 'LogScaler']
      flag_pipe: 
        basic:
          ['Inputter:-1']
      float_pipe: 
        basic:
          ['Inputter:missing']
        stats:
          ['Truncate_99']
    training:
      features_path: 'C:\\Users\\doube\\o2sk\\o2sk-utils\\data\\features\\'
      labels_path: 'C:\\Users\\doube\\o2sk\\o2sk-utils\\data\\labels\\'
      stats_path: 'C:\\Users\\doube\\o2sk\\stats.json'
      split_col: 'ID_COL_MONTH'
      train_path: 'C:\\Users\\doube\\o2sk\\o2sk-utils\\train'
      valid_path: 'C:\\Users\\doube\\o2sk\\o2sk-utils\\valid'
      test_path: 'C:\\Users\\doube\\o2sk\\o2sk-utils\\test'
      shift_join: -1
      test_months: 0
    scoring:
      features_path: 'C:\\Users\\doube\\o2sk\\o2sk-utils\\data\\features\\'
      stats_path: 'C:\\Users\\doube\\o2sk\\stats.json'
      scoring_output_path: 'C:\\Users\\doube\\o2sk\\o2sk-utils\\scoring'
modeling:
    mode: 'hyperopt' # runs hyperparameter optimization. If cv it takes the best_params from best_params path
    eval_metric: 'aucpr' # mlogloss for multiclass, aucpr for binary
    objective: 'binary:logistic' # multi:softprob for multiclass, binary:logistic for binary
    scale_pos_weight: '400'
    num_class: 2
    max_depth: [5, 30] # 50
    eta: [0.001, 0.01]   # 0.01
    subsample: [0.01, 0.6]
    gamma: [1, 30]
    min_child_weight: [1, 50]
    colsample_bytree: [0.3, 1]
    safe_cols: ['ID_CUSTOMER', 'LABEL', 'CD_PERIOD']
    label_col: 'LABEL'
    n_trials: 4 # how many different hyperparameters tries
    docker_config_path: /home/frovis/o2_sk/xgboost-python-pyspark/docker/config_training.yml
    data_path: /home/frovis/o2_sk/xgboost-python-pyspark/docker/data/
    log_path: /home/frovis/o2_sk/xgboost-python-pyspark/docker/experiment/binary_training.log
    params_result_path: /home/frovis/o2_sk/xgboost-python-pyspark/docker/experiment/binary_results.csv
    best_params_path: /home/frovis/o2_sk/xgboost-python-pyspark/docker/experiment/binary.yml
    model_path: /home/frovis/o2_sk/xgboost-python-pyspark/docker/experiment/
    spark_config:
      'spark.default.parallelism': '100'
      'spark.dynamicAllocation.enabled': 'false'
      'spark.driver.memory': '10g'
      'spark.driver.cores': '4'
      'spark.driver.memoryOverhead': '4g'
      'spark.driver.maxResultSize': '10g'
      'spark.executor.memory': '10g'
      'spark.executor.cores': '4'
      'spark.executor.memoryOverhead': '4g'
      'spark.executor.instances': '3'
      'spark.executor.heartbeatInterval': '120s'
      'spark.network.timeout': '12000s'
      'spark.sql.inMemoryColumnarStorage.compressed': 'true'
      'spark.sql.autoBroadcastJoinThreshold': -1
      'spark.serializer': 'org.apache.spark.serializer.KryoSerializer'
scoring:
    safe_cols: ['ID_CUSTOMER', 'LABEL', 'CD_PERIOD']
    model_path: '/home/frovis/o2_sk/xgboost-python-pyspark/docker/experiment/model.bin'
    data_path: '/home/frovis/o2_sk/xgboost-python-pyspark/docker/data/'
    scoring_output_path: '/home/frovis/o2_sk/xgboost-python-pyspark/docker/experiment/'
    docker_config_path: /home/frovis/o2_sk/xgboost-python-pyspark/docker/config_scoring.yml
    spark_config:
      'spark.default.parallelism': '100'
      'spark.dynamicAllocation.enabled': 'false'
      'spark.driver.memory': '10g'
      'spark.driver.cores': '4'
      'spark.driver.memoryOverhead': '4g'
      'spark.driver.maxResultSize': '10g'
      'spark.executor.memory': '10g'
      'spark.executor.cores': '4'
      'spark.executor.memoryOverhead': '4g'
      'spark.executor.instances': '3'
      'spark.executor.heartbeatInterval': '120s'
      'spark.network.timeout': '12000s'
      'spark.sql.inMemoryColumnarStorage.compressed': 'true'
      'spark.sql.autoBroadcastJoinThreshold': -1
      'spark.serializer': 'org.apache.spark.serializer.KryoSerializer'
auth_cfg: '/home/o2spark/config.ini'


# finish saving log of trials
